# MyUselessPlugin, version 0.7; config version 1
# ----------------------------------------------------------------
# This is MyUselessPlugin's config
# Haven't nailed it yet, so it is very basic.
trolls:
  blow: true
  crackhead: true
  kaboom: true
functions:
  throwable-fireball: true
  one-player-sleep: true

