name: MyUselessPlugin
version: 0.8-SNAPSHOT
main: me.spike.main
api-version: 1.17
authors: [ SpikeVN ]
description: A rewritten Useless Plugin
commands:
  blow:
    description: Blows someone up.
    usage: /blow <player>
    aliases: [tnt, boom]
  crackhead:
    description: Summons an anvil to crack someone's head.
    usage: /crackhead <player>
    aliases: [vodau]
  mup:
    description: The main plugin command.
    usage: /mup
    aliases: [myuselessplugin, uselessplugin]
  kaboom:
    description: Ka-boom
    usage: /kaboom <player>
